/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DisparoEmMassaWhatsappRouteImport } from './routes/disparo-em-massa-whatsapp'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ParaSegurosRouteImport } from './routes/para.seguros'
import { Route as ParaEnergiaSolarRouteImport } from './routes/para.energia-solar'
import { Route as ParaCorretorDeImoveisRouteImport } from './routes/para.corretor-de-imoveis'
import { Route as ParaContabilidadeRouteImport } from './routes/para.contabilidade'
import { Route as ParaAgenciasRouteImport } from './routes/para.agencias'
import { Route as ParaAdvocaciaRouteImport } from './routes/para.advocacia'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppSequenciasRouteImport } from './routes/app.sequencias'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppOnboardingRouteImport } from './routes/app.onboarding'
import { Route as AppMapaRouteImport } from './routes/app.mapa'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppIaVendasRouteImport } from './routes/app.ia-vendas'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppFollowUpsRouteImport } from './routes/app.follow-ups'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppCampanhasRouteImport } from './routes/app.campanhas'
import { Route as AppBuscarRouteImport } from './routes/app.buscar'
import { Route as AppAfiliadosRouteImport } from './routes/app.afiliados'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppCampanhasNovaRouteImport } from './routes/app.campanhas.nova'
import { Route as ApiPublicUazapiWebhookRouteImport } from './routes/api/public/uazapi-webhook'
import { Route as ApiPublicKiwifyWebhookRouteImport } from './routes/api/public/kiwify-webhook'
import { Route as ApiPublicHooksProcessFollowupsRouteImport } from './routes/api/public/hooks/process-followups'
import { Route as ApiPublicHooksProcessCampaignsRouteImport } from './routes/api/public/hooks/process-campaigns'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparoEmMassaWhatsappRoute = DisparoEmMassaWhatsappRouteImport.update({
  id: '/disparo-em-massa-whatsapp',
  path: '/disparo-em-massa-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ParaSegurosRoute = ParaSegurosRouteImport.update({
  id: '/para/seguros',
  path: '/para/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaEnergiaSolarRoute = ParaEnergiaSolarRouteImport.update({
  id: '/para/energia-solar',
  path: '/para/energia-solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaCorretorDeImoveisRoute = ParaCorretorDeImoveisRouteImport.update({
  id: '/para/corretor-de-imoveis',
  path: '/para/corretor-de-imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaContabilidadeRoute = ParaContabilidadeRouteImport.update({
  id: '/para/contabilidade',
  path: '/para/contabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaAgenciasRoute = ParaAgenciasRouteImport.update({
  id: '/para/agencias',
  path: '/para/agencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaAdvocaciaRoute = ParaAdvocaciaRouteImport.update({
  id: '/para/advocacia',
  path: '/para/advocacia',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSequenciasRoute = AppSequenciasRouteImport.update({
  id: '/sequencias',
  path: '/sequencias',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppIaVendasRoute = AppIaVendasRouteImport.update({
  id: '/ia-vendas',
  path: '/ia-vendas',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)
const AppAfiliadosRoute = AppAfiliadosRouteImport.update({
  id: '/afiliados',
  path: '/afiliados',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasNovaRoute = AppCampanhasNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AppCampanhasRoute,
} as any)
const ApiPublicUazapiWebhookRoute = ApiPublicUazapiWebhookRouteImport.update({
  id: '/api/public/uazapi-webhook',
  path: '/api/public/uazapi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKiwifyWebhookRoute = ApiPublicKiwifyWebhookRouteImport.update({
  id: '/api/public/kiwify-webhook',
  path: '/api/public/kiwify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessFollowupsRoute =
  ApiPublicHooksProcessFollowupsRouteImport.update({
    id: '/api/public/hooks/process-followups',
    path: '/api/public/hooks/process-followups',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessCampaignsRoute =
  ApiPublicHooksProcessCampaignsRouteImport.update({
    id: '/api/public/hooks/process-campaigns',
    path: '/api/public/hooks/process-campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disparo-em-massa-whatsapp': typeof DisparoEmMassaWhatsappRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRoute
  '/app/afiliados': typeof AppAfiliadosRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/campanhas': typeof AppCampanhasRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/ia': typeof AppIaRoute
  '/app/ia-vendas': typeof AppIaVendasRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/sequencias': typeof AppSequenciasRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/para/advocacia': typeof ParaAdvocaciaRoute
  '/para/agencias': typeof ParaAgenciasRoute
  '/para/contabilidade': typeof ParaContabilidadeRoute
  '/para/corretor-de-imoveis': typeof ParaCorretorDeImoveisRoute
  '/para/energia-solar': typeof ParaEnergiaSolarRoute
  '/para/seguros': typeof ParaSegurosRoute
  '/app/': typeof AppIndexRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
  '/api/public/uazapi-webhook': typeof ApiPublicUazapiWebhookRoute
  '/app/campanhas/nova': typeof AppCampanhasNovaRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disparo-em-massa-whatsapp': typeof DisparoEmMassaWhatsappRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRoute
  '/app/afiliados': typeof AppAfiliadosRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/campanhas': typeof AppCampanhasRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/ia': typeof AppIaRoute
  '/app/ia-vendas': typeof AppIaVendasRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/sequencias': typeof AppSequenciasRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/para/advocacia': typeof ParaAdvocaciaRoute
  '/para/agencias': typeof ParaAgenciasRoute
  '/para/contabilidade': typeof ParaContabilidadeRoute
  '/para/corretor-de-imoveis': typeof ParaCorretorDeImoveisRoute
  '/para/energia-solar': typeof ParaEnergiaSolarRoute
  '/para/seguros': typeof ParaSegurosRoute
  '/app': typeof AppIndexRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
  '/api/public/uazapi-webhook': typeof ApiPublicUazapiWebhookRoute
  '/app/campanhas/nova': typeof AppCampanhasNovaRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/disparo-em-massa-whatsapp': typeof DisparoEmMassaWhatsappRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/admin': typeof AppAdminRoute
  '/app/afiliados': typeof AppAfiliadosRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/campanhas': typeof AppCampanhasRouteWithChildren
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/ia': typeof AppIaRoute
  '/app/ia-vendas': typeof AppIaVendasRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/sequencias': typeof AppSequenciasRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/para/advocacia': typeof ParaAdvocaciaRoute
  '/para/agencias': typeof ParaAgenciasRoute
  '/para/contabilidade': typeof ParaContabilidadeRoute
  '/para/corretor-de-imoveis': typeof ParaCorretorDeImoveisRoute
  '/para/energia-solar': typeof ParaEnergiaSolarRoute
  '/para/seguros': typeof ParaSegurosRoute
  '/app/': typeof AppIndexRoute
  '/api/public/kiwify-webhook': typeof ApiPublicKiwifyWebhookRoute
  '/api/public/uazapi-webhook': typeof ApiPublicUazapiWebhookRoute
  '/app/campanhas/nova': typeof AppCampanhasNovaRoute
  '/api/public/hooks/process-campaigns': typeof ApiPublicHooksProcessCampaignsRoute
  '/api/public/hooks/process-followups': typeof ApiPublicHooksProcessFollowupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/blog'
    | '/cadastro'
    | '/configuracoes'
    | '/disparo-em-massa-whatsapp'
    | '/login'
    | '/planos'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app/admin'
    | '/app/afiliados'
    | '/app/buscar'
    | '/app/campanhas'
    | '/app/configuracoes'
    | '/app/follow-ups'
    | '/app/ia'
    | '/app/ia-vendas'
    | '/app/leads'
    | '/app/mapa'
    | '/app/onboarding'
    | '/app/relatorios'
    | '/app/sequencias'
    | '/app/templates'
    | '/app/whatsapp'
    | '/para/advocacia'
    | '/para/agencias'
    | '/para/contabilidade'
    | '/para/corretor-de-imoveis'
    | '/para/energia-solar'
    | '/para/seguros'
    | '/app/'
    | '/api/public/kiwify-webhook'
    | '/api/public/uazapi-webhook'
    | '/app/campanhas/nova'
    | '/api/public/hooks/process-campaigns'
    | '/api/public/hooks/process-followups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/cadastro'
    | '/configuracoes'
    | '/disparo-em-massa-whatsapp'
    | '/login'
    | '/planos'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app/admin'
    | '/app/afiliados'
    | '/app/buscar'
    | '/app/campanhas'
    | '/app/configuracoes'
    | '/app/follow-ups'
    | '/app/ia'
    | '/app/ia-vendas'
    | '/app/leads'
    | '/app/mapa'
    | '/app/onboarding'
    | '/app/relatorios'
    | '/app/sequencias'
    | '/app/templates'
    | '/app/whatsapp'
    | '/para/advocacia'
    | '/para/agencias'
    | '/para/contabilidade'
    | '/para/corretor-de-imoveis'
    | '/para/energia-solar'
    | '/para/seguros'
    | '/app'
    | '/api/public/kiwify-webhook'
    | '/api/public/uazapi-webhook'
    | '/app/campanhas/nova'
    | '/api/public/hooks/process-campaigns'
    | '/api/public/hooks/process-followups'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/blog'
    | '/cadastro'
    | '/configuracoes'
    | '/disparo-em-massa-whatsapp'
    | '/login'
    | '/planos'
    | '/recuperar-senha'
    | '/reset-password'
    | '/sitemap.xml'
    | '/app/admin'
    | '/app/afiliados'
    | '/app/buscar'
    | '/app/campanhas'
    | '/app/configuracoes'
    | '/app/follow-ups'
    | '/app/ia'
    | '/app/ia-vendas'
    | '/app/leads'
    | '/app/mapa'
    | '/app/onboarding'
    | '/app/relatorios'
    | '/app/sequencias'
    | '/app/templates'
    | '/app/whatsapp'
    | '/para/advocacia'
    | '/para/agencias'
    | '/para/contabilidade'
    | '/para/corretor-de-imoveis'
    | '/para/energia-solar'
    | '/para/seguros'
    | '/app/'
    | '/api/public/kiwify-webhook'
    | '/api/public/uazapi-webhook'
    | '/app/campanhas/nova'
    | '/api/public/hooks/process-campaigns'
    | '/api/public/hooks/process-followups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DisparoEmMassaWhatsappRoute: typeof DisparoEmMassaWhatsappRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ParaAdvocaciaRoute: typeof ParaAdvocaciaRoute
  ParaAgenciasRoute: typeof ParaAgenciasRoute
  ParaContabilidadeRoute: typeof ParaContabilidadeRoute
  ParaCorretorDeImoveisRoute: typeof ParaCorretorDeImoveisRoute
  ParaEnergiaSolarRoute: typeof ParaEnergiaSolarRoute
  ParaSegurosRoute: typeof ParaSegurosRoute
  ApiPublicKiwifyWebhookRoute: typeof ApiPublicKiwifyWebhookRoute
  ApiPublicUazapiWebhookRoute: typeof ApiPublicUazapiWebhookRoute
  ApiPublicHooksProcessCampaignsRoute: typeof ApiPublicHooksProcessCampaignsRoute
  ApiPublicHooksProcessFollowupsRoute: typeof ApiPublicHooksProcessFollowupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparo-em-massa-whatsapp': {
      id: '/disparo-em-massa-whatsapp'
      path: '/disparo-em-massa-whatsapp'
      fullPath: '/disparo-em-massa-whatsapp'
      preLoaderRoute: typeof DisparoEmMassaWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/para/seguros': {
      id: '/para/seguros'
      path: '/para/seguros'
      fullPath: '/para/seguros'
      preLoaderRoute: typeof ParaSegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/energia-solar': {
      id: '/para/energia-solar'
      path: '/para/energia-solar'
      fullPath: '/para/energia-solar'
      preLoaderRoute: typeof ParaEnergiaSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/corretor-de-imoveis': {
      id: '/para/corretor-de-imoveis'
      path: '/para/corretor-de-imoveis'
      fullPath: '/para/corretor-de-imoveis'
      preLoaderRoute: typeof ParaCorretorDeImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/contabilidade': {
      id: '/para/contabilidade'
      path: '/para/contabilidade'
      fullPath: '/para/contabilidade'
      preLoaderRoute: typeof ParaContabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/agencias': {
      id: '/para/agencias'
      path: '/para/agencias'
      fullPath: '/para/agencias'
      preLoaderRoute: typeof ParaAgenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/advocacia': {
      id: '/para/advocacia'
      path: '/para/advocacia'
      fullPath: '/para/advocacia'
      preLoaderRoute: typeof ParaAdvocaciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sequencias': {
      id: '/app/sequencias'
      path: '/sequencias'
      fullPath: '/app/sequencias'
      preLoaderRoute: typeof AppSequenciasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mapa': {
      id: '/app/mapa'
      path: '/mapa'
      fullPath: '/app/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia-vendas': {
      id: '/app/ia-vendas'
      path: '/ia-vendas'
      fullPath: '/app/ia-vendas'
      preLoaderRoute: typeof AppIaVendasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/follow-ups': {
      id: '/app/follow-ups'
      path: '/follow-ups'
      fullPath: '/app/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campanhas': {
      id: '/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buscar': {
      id: '/app/buscar'
      path: '/buscar'
      fullPath: '/app/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/afiliados': {
      id: '/app/afiliados'
      path: '/afiliados'
      fullPath: '/app/afiliados'
      preLoaderRoute: typeof AppAfiliadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campanhas/nova': {
      id: '/app/campanhas/nova'
      path: '/nova'
      fullPath: '/app/campanhas/nova'
      preLoaderRoute: typeof AppCampanhasNovaRouteImport
      parentRoute: typeof AppCampanhasRoute
    }
    '/api/public/uazapi-webhook': {
      id: '/api/public/uazapi-webhook'
      path: '/api/public/uazapi-webhook'
      fullPath: '/api/public/uazapi-webhook'
      preLoaderRoute: typeof ApiPublicUazapiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kiwify-webhook': {
      id: '/api/public/kiwify-webhook'
      path: '/api/public/kiwify-webhook'
      fullPath: '/api/public/kiwify-webhook'
      preLoaderRoute: typeof ApiPublicKiwifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-followups': {
      id: '/api/public/hooks/process-followups'
      path: '/api/public/hooks/process-followups'
      fullPath: '/api/public/hooks/process-followups'
      preLoaderRoute: typeof ApiPublicHooksProcessFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-campaigns': {
      id: '/api/public/hooks/process-campaigns'
      path: '/api/public/hooks/process-campaigns'
      fullPath: '/api/public/hooks/process-campaigns'
      preLoaderRoute: typeof ApiPublicHooksProcessCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppCampanhasRouteChildren {
  AppCampanhasNovaRoute: typeof AppCampanhasNovaRoute
}

const AppCampanhasRouteChildren: AppCampanhasRouteChildren = {
  AppCampanhasNovaRoute: AppCampanhasNovaRoute,
}

const AppCampanhasRouteWithChildren = AppCampanhasRoute._addFileChildren(
  AppCampanhasRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAfiliadosRoute: typeof AppAfiliadosRoute
  AppBuscarRoute: typeof AppBuscarRoute
  AppCampanhasRoute: typeof AppCampanhasRouteWithChildren
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppIaRoute: typeof AppIaRoute
  AppIaVendasRoute: typeof AppIaVendasRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMapaRoute: typeof AppMapaRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppSequenciasRoute: typeof AppSequenciasRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAfiliadosRoute: AppAfiliadosRoute,
  AppBuscarRoute: AppBuscarRoute,
  AppCampanhasRoute: AppCampanhasRouteWithChildren,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppIaRoute: AppIaRoute,
  AppIaVendasRoute: AppIaVendasRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMapaRoute: AppMapaRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppSequenciasRoute: AppSequenciasRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DisparoEmMassaWhatsappRoute: DisparoEmMassaWhatsappRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ParaAdvocaciaRoute: ParaAdvocaciaRoute,
  ParaAgenciasRoute: ParaAgenciasRoute,
  ParaContabilidadeRoute: ParaContabilidadeRoute,
  ParaCorretorDeImoveisRoute: ParaCorretorDeImoveisRoute,
  ParaEnergiaSolarRoute: ParaEnergiaSolarRoute,
  ParaSegurosRoute: ParaSegurosRoute,
  ApiPublicKiwifyWebhookRoute: ApiPublicKiwifyWebhookRoute,
  ApiPublicUazapiWebhookRoute: ApiPublicUazapiWebhookRoute,
  ApiPublicHooksProcessCampaignsRoute: ApiPublicHooksProcessCampaignsRoute,
  ApiPublicHooksProcessFollowupsRoute: ApiPublicHooksProcessFollowupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
