/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DisparoEmMassaWhatsappRouteImport } from './routes/disparo-em-massa-whatsapp'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ParaSegurosRouteImport } from './routes/para.seguros'
import { Route as ParaEnergiaSolarRouteImport } from './routes/para.energia-solar'
import { Route as ParaCorretorDeImoveisRouteImport } from './routes/para.corretor-de-imoveis'
import { Route as ParaContabilidadeRouteImport } from './routes/para.contabilidade'
import { Route as ParaAgenciasRouteImport } from './routes/para.agencias'
import { Route as ParaAdvocaciaRouteImport } from './routes/para.advocacia'
import { Route as AppWhatsappRouteImport } from './routes/app.whatsapp'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppMapaRouteImport } from './routes/app.mapa'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppCampanhasRouteImport } from './routes/app.campanhas'
import { Route as AppBuscarRouteImport } from './routes/app.buscar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DisparoEmMassaWhatsappRoute = DisparoEmMassaWhatsappRouteImport.update({
  id: '/disparo-em-massa-whatsapp',
  path: '/disparo-em-massa-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ParaSegurosRoute = ParaSegurosRouteImport.update({
  id: '/para/seguros',
  path: '/para/seguros',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaEnergiaSolarRoute = ParaEnergiaSolarRouteImport.update({
  id: '/para/energia-solar',
  path: '/para/energia-solar',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaCorretorDeImoveisRoute = ParaCorretorDeImoveisRouteImport.update({
  id: '/para/corretor-de-imoveis',
  path: '/para/corretor-de-imoveis',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaContabilidadeRoute = ParaContabilidadeRouteImport.update({
  id: '/para/contabilidade',
  path: '/para/contabilidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaAgenciasRoute = ParaAgenciasRouteImport.update({
  id: '/para/agencias',
  path: '/para/agencias',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaAdvocaciaRoute = ParaAdvocaciaRouteImport.update({
  id: '/para/advocacia',
  path: '/para/advocacia',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppMapaRoute = AppMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppBuscarRoute = AppBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/disparo-em-massa-whatsapp': typeof DisparoEmMassaWhatsappRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/ia': typeof AppIaRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/para/advocacia': typeof ParaAdvocaciaRoute
  '/para/agencias': typeof ParaAgenciasRoute
  '/para/contabilidade': typeof ParaContabilidadeRoute
  '/para/corretor-de-imoveis': typeof ParaCorretorDeImoveisRoute
  '/para/energia-solar': typeof ParaEnergiaSolarRoute
  '/para/seguros': typeof ParaSegurosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/disparo-em-massa-whatsapp': typeof DisparoEmMassaWhatsappRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/ia': typeof AppIaRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/para/advocacia': typeof ParaAdvocaciaRoute
  '/para/agencias': typeof ParaAgenciasRoute
  '/para/contabilidade': typeof ParaContabilidadeRoute
  '/para/corretor-de-imoveis': typeof ParaCorretorDeImoveisRoute
  '/para/energia-solar': typeof ParaEnergiaSolarRoute
  '/para/seguros': typeof ParaSegurosRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRoute
  '/cadastro': typeof CadastroRoute
  '/disparo-em-massa-whatsapp': typeof DisparoEmMassaWhatsappRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/buscar': typeof AppBuscarRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/ia': typeof AppIaRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/mapa': typeof AppMapaRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/templates': typeof AppTemplatesRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/para/advocacia': typeof ParaAdvocaciaRoute
  '/para/agencias': typeof ParaAgenciasRoute
  '/para/contabilidade': typeof ParaContabilidadeRoute
  '/para/corretor-de-imoveis': typeof ParaCorretorDeImoveisRoute
  '/para/energia-solar': typeof ParaEnergiaSolarRoute
  '/para/seguros': typeof ParaSegurosRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/blog'
    | '/cadastro'
    | '/disparo-em-massa-whatsapp'
    | '/login'
    | '/planos'
    | '/sitemap.xml'
    | '/app/buscar'
    | '/app/campanhas'
    | '/app/configuracoes'
    | '/app/ia'
    | '/app/leads'
    | '/app/mapa'
    | '/app/relatorios'
    | '/app/templates'
    | '/app/whatsapp'
    | '/para/advocacia'
    | '/para/agencias'
    | '/para/contabilidade'
    | '/para/corretor-de-imoveis'
    | '/para/energia-solar'
    | '/para/seguros'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/cadastro'
    | '/disparo-em-massa-whatsapp'
    | '/login'
    | '/planos'
    | '/sitemap.xml'
    | '/app/buscar'
    | '/app/campanhas'
    | '/app/configuracoes'
    | '/app/ia'
    | '/app/leads'
    | '/app/mapa'
    | '/app/relatorios'
    | '/app/templates'
    | '/app/whatsapp'
    | '/para/advocacia'
    | '/para/agencias'
    | '/para/contabilidade'
    | '/para/corretor-de-imoveis'
    | '/para/energia-solar'
    | '/para/seguros'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/blog'
    | '/cadastro'
    | '/disparo-em-massa-whatsapp'
    | '/login'
    | '/planos'
    | '/sitemap.xml'
    | '/app/buscar'
    | '/app/campanhas'
    | '/app/configuracoes'
    | '/app/ia'
    | '/app/leads'
    | '/app/mapa'
    | '/app/relatorios'
    | '/app/templates'
    | '/app/whatsapp'
    | '/para/advocacia'
    | '/para/agencias'
    | '/para/contabilidade'
    | '/para/corretor-de-imoveis'
    | '/para/energia-solar'
    | '/para/seguros'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRoute
  CadastroRoute: typeof CadastroRoute
  DisparoEmMassaWhatsappRoute: typeof DisparoEmMassaWhatsappRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ParaAdvocaciaRoute: typeof ParaAdvocaciaRoute
  ParaAgenciasRoute: typeof ParaAgenciasRoute
  ParaContabilidadeRoute: typeof ParaContabilidadeRoute
  ParaCorretorDeImoveisRoute: typeof ParaCorretorDeImoveisRoute
  ParaEnergiaSolarRoute: typeof ParaEnergiaSolarRoute
  ParaSegurosRoute: typeof ParaSegurosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disparo-em-massa-whatsapp': {
      id: '/disparo-em-massa-whatsapp'
      path: '/disparo-em-massa-whatsapp'
      fullPath: '/disparo-em-massa-whatsapp'
      preLoaderRoute: typeof DisparoEmMassaWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/para/seguros': {
      id: '/para/seguros'
      path: '/para/seguros'
      fullPath: '/para/seguros'
      preLoaderRoute: typeof ParaSegurosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/energia-solar': {
      id: '/para/energia-solar'
      path: '/para/energia-solar'
      fullPath: '/para/energia-solar'
      preLoaderRoute: typeof ParaEnergiaSolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/corretor-de-imoveis': {
      id: '/para/corretor-de-imoveis'
      path: '/para/corretor-de-imoveis'
      fullPath: '/para/corretor-de-imoveis'
      preLoaderRoute: typeof ParaCorretorDeImoveisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/contabilidade': {
      id: '/para/contabilidade'
      path: '/para/contabilidade'
      fullPath: '/para/contabilidade'
      preLoaderRoute: typeof ParaContabilidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/agencias': {
      id: '/para/agencias'
      path: '/para/agencias'
      fullPath: '/para/agencias'
      preLoaderRoute: typeof ParaAgenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para/advocacia': {
      id: '/para/advocacia'
      path: '/para/advocacia'
      fullPath: '/para/advocacia'
      preLoaderRoute: typeof ParaAdvocaciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mapa': {
      id: '/app/mapa'
      path: '/mapa'
      fullPath: '/app/mapa'
      preLoaderRoute: typeof AppMapaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campanhas': {
      id: '/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/buscar': {
      id: '/app/buscar'
      path: '/buscar'
      fullPath: '/app/buscar'
      preLoaderRoute: typeof AppBuscarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuscarRoute: typeof AppBuscarRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppIaRoute: typeof AppIaRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMapaRoute: typeof AppMapaRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuscarRoute: AppBuscarRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppIaRoute: AppIaRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMapaRoute: AppMapaRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRoute,
  CadastroRoute: CadastroRoute,
  DisparoEmMassaWhatsappRoute: DisparoEmMassaWhatsappRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ParaAdvocaciaRoute: ParaAdvocaciaRoute,
  ParaAgenciasRoute: ParaAgenciasRoute,
  ParaContabilidadeRoute: ParaContabilidadeRoute,
  ParaCorretorDeImoveisRoute: ParaCorretorDeImoveisRoute,
  ParaEnergiaSolarRoute: ParaEnergiaSolarRoute,
  ParaSegurosRoute: ParaSegurosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
